### ISSUE TITLE
Not detecting credentials

### ISSUE THREAD

**Issue by djh82uk** [Skyscanner/sonar-secrets#1]
Hi, I wanted to have a bit of a play around with this, I have an example nodejs projects, and I have hardcoded variables (with values) for username and password.

But nothing gets detected within sonarQube.

I have created a new quality profile for JS and included the 5 rules with the skyscanner tag.

Just wondering what I could be doing wrong.

**Comment by adeptex** [comment]
Hey there. Are you scanning your project with the new profile that you created?

**Comment by djh82uk** [comment]
Hi, yes i set the new custom profile as default and re ran the ci steps and it shows that the profile was last used x seconds ago etc

Thanks

**Comment by adeptex** [comment]
Please provide some sample code so I can try to reproduce the issue

**Comment by mulakkalfaizal** [comment]
its not detecting from my code also..
