### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by felipecruz91** [Skyscanner/sonar-secrets#4]
When running `cd sonar-secrets/java && mvn clean package` I get the following error:

[ERROR] Failures:
[ERROR]   APIKeysTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   AWSCredentialsTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   HighEntropyTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   PasswordsTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   PrivateKeysTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.

**Comment by adeptex** [comment]
Hi @felipecruz91, could you please provide more details about your system, Java version, etc etc?

sonar-secrets is tested in OSX and Linux with Java 8

**Comment by punnarao-kommineni** [comment]
Hi,

I am facing following error when i build:

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.119 s <<< FAILURE! - in org.sonar.skyscanner.java.checks.AWSCredentialsTest
[ERROR] org.sonar.skyscanner.java.checks.AWSCredentialsTest.test  Time elapsed: 0.118 s  <<< FAILURE!
java.lang.AssertionError: Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
        at org.sonar.skyscanner.java.checks.AWSCredentialsTest.test(AWSCredentialsTest.java:23)

[INFO] Running org.sonar.skyscanner.java.MyJavaRulesDefinitionTest
04:04:47.316 [Report about progress of Java AST analyzer] INFO  org.sonar.squidbridge.ProgressReport - 1/1 source files have been analyzed
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.136 s - in org.sonar.skyscanner.java.MyJavaRulesDefinitionTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   APIKeysTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   AWSCredentialsTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   HighEntropyTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   PasswordsTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[ERROR]   PrivateKeysTest.test:23 Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
[INFO]
[ERROR] Tests run: 6, Failures: 5, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.120 s
[INFO] Finished at: 2020-07-15T04:04:47+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project sonar-secrets-java: There are test failures.
[ERROR]
[ERROR] Please refer to /opt/sonar-secrets/java/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Following are the system details:

OS: Cent OS 7U8
Java Version: Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Maven Version: Apache Maven 3.6.3 

Can you help me to fix the issue.

**Comment by felipecruz91** [comment]
It would be very beneficial to create a Dockerfile for this project with the dependencies the project requires to be built. That would solve the issue.

**Comment by felipecruz91** [comment]
Hi @punnarao-kommineni ,

Verify you have Java 8 installed. Otherwise, you can follow the instructions here to build the project with Docker:

https://github.com/Skyscanner/sonar-secrets/pull/5/files

/cc @adeptex

**Comment by punnarao-kommineni** [comment]
Thanks. I will try and let you know.

**Comment by adeptex** [comment]
Hi all, sorry for a long delay on this. The issue indeed is with Java8 vs 11. I've added Github Actions build with Java 8 where you can see that that the build works as expected - https://github.com/Skyscanner/sonar-secrets/runs/2150962423

Going forward, it will be a good improvement to make this compile correctly with Java 11. Notably, the JavaScript jar seems to compile and test fine with 11. Fixing Java jar tests will require some investigation and dev work.

There are also pre-built jars available - https://github.com/Skyscanner/sonar-secrets/releases/tag/v1.3.0
